POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Leonardo",
  "last_name": "Dicaprio",
  "known_for": "Titanic",
  "gender": "male",
  "age": 50
}

###
POST http://localhost:3000/movies.json
Content-Type: application/json

{
  "title": "The Big Lebowsi",
  "year": 1999,
  "plot": "The Dude Abides.",
  "director": "Cohen Bro's",
  "english": false
}

###
PATCH http://localhost:3000/movies/25.json
Content-Type: application/json

{
  "english": true
}

###
PATCH http://localhost:3000/actors/69.json
Content-Type: application/json

{
  "last_name": "DiCaprio",
  "known_for": "Inception, The Revenant",
  "age": 51
}

###
DELETE http://localhost:3000/movies/23.json
Content-Type: application/json

###
DELETE http://localhost:3000/actors/68.json
Content-Type: application/json