
###ACTOR REQUESTS###
#CREATE
POST http://localhost:3000/actors.json
Content-Type: application/json

{
  "first_name": "Young",
  "last_name": "Jones",
  "gender": "male",
  "age": 14,
  "movie_id": 1
}

###
#UPDATE
PATCH http://localhost:3000/actors/69.json
Content-Type: application/json

{
  "last_name": "DiCaprio",
  "known_for": "Inception, The Revenant",
  "age": 51
}

###
#DELETE
DELETE http://localhost:3000/actors/68.json
Content-Type: application/json

###MOVIE REQUESTS 

###
#INDEX
GET http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2MzU2MDczOTF9.Yw4j6lZf8NYwMhjJZhXAD3IkE74MZ_tJ_6C-0sw7q_I

#CREATE
###
POST http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU1MTM2NjN9.WLF837nXfcDVDcDKwZy4R7nyv1R9B-3O8JzWpPApACk
Content-Type: application/json

{
  "title": "A movie",
  "year": 2008,
  "plot": "Does movie stuff.",
  "director": "IDK",
  "english": true
}

###
#UPDATE
PATCH http://localhost:3000/movies/31.json
Content-Type: application/json

{
  "year": 1998,
  "english": true
}



###
#DELETE
DELETE http://localhost:3000/movies/34.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2MzU1MTM2NjN9.WLF837nXfcDVDcDKwZy4R7nyv1R9B-3O8JzWpPApACk
Content-Type: application/json




###USER REQUESTS
### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Ian name",
  "email": "ian@test.com",
  "password": "password",
  "password_confirmation": "password"
}


### Sessions create (login)
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}


###MOVIE GENRE REQUESTS
###CREATE
POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id": 1,
  "genre_id": 1
}